name: Deploy Customer Azure Enterprise Scale Landing Zone PNK2
on:
  push:
      branches: [ main ]
  workflow_dispatch:

env:
ENABLED_ID:'test'

jobs:
  
  
  Add-Rootrights:
    uses: ./.github/workflows/1-pnk-addrootrights.yml
    with:
      condition: eq('${{ env.ENABLED_ID}}', true)
      Subscription_Id: '8cdd9893-afc4-4a42-8060-db0558c395f4'
      CustomerId: 'pnk'
      CustomerFullName: 'PinkElephant'
      Location: 'westeurope'
    secrets: inherit
    
  Add-Rootgroups:
    uses: ./.github/workflows/2-pnk-addrootgroups.yml
    needs: Add-Rootrights
    with:
      condition: eq('${{ env.ENABLED_ID}}', true)
      Subscription_Id: '8cdd9893-afc4-4a42-8060-db0558c395f4'
      CustomerId: 'pnk'
      CustomerFullName: 'PinkElephant'
      Location: 'westeurope'
    secrets: inherit  
    

