name: Deploy Customer Azure Enterprise Scale Landing Zone PNK1
on:
  push:
      branches: [ main ]
  workflow_dispatch:


jobs:
  
  deploy-RG:
    uses: ./.github/workflows/1-pnk-reourcegroups.yml
    with:
      Subscription_Id: '8cdd9893-afc4-4a42-8060-db0558c395f4'
      CustomerId: 'pnk'
      Location: 'westeurope'
    secrets: inherit
