name: Deploy Customer Azure Enterprise Scale Landing Zone PNK2
on:
  push:
      branches: [ main ]
  workflow_dispatch:


jobs:
  
  
  deploy-MG:
    uses: ./.github/workflows/1-pnk-managementgroups.yml
    with:
      Subscription_Id: '8cdd9893-afc4-4a42-8060-db0558c395f4'
      CustomerId: 'pnk'
      CustomerFullName: 'Pink Elephant'
      Location: 'westeurope'
    secrets: inherit



