name: Deploy Resource Groups

on:
  workflow_call:
    inputs:
      Subscription_Id:
        required: true
        type: string
      CustomerId:
        required: true
        type: string
      Location:
        required: true
        type: string

jobs:
  deploy-resourcegroups:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ inputs.Subscription_Id }}
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: Create Resource Groups
        id: resourceGroups
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: modules/rg/resourcegroups.json
          parameters: >
            modules/rg/resourcegroups.parameters.json
            CustomerId=${{ inputs.CustomerId }}
            resourceGroupLocation=${{ inputs.Location }}
            
    outputs:
          Subscription_Id: ${{ steps.resourcegroups.outputs.Subscription_Id }}
          CustomerId: ${{ steps.resourcegroups.outputs.CustomerId }}


