name: Deploy Customer Azure Enterprise Scale Landing Zone PNK2

on:
  push:
      branches: [ main ]
      
  workflow_dispatch:
    inputs:
      customerfullname:
        description: Geef de volledige klantnaame op zonder spaties
        required: true  
      customerid:
        description: Vul hier klant ID in
        required: true
      subscription_lzid:
        description: Vul hier de subscription ID in van de klant landingzone (LZ)
        required: true
      subscription_plcon:
        description: Vul hier de subscription ID in van de "connectivity" subscription (PL)
        required: true
      subscription_plide:
        description: Vul hier de subscription ID in van de "identity" subscription (PL)
        required: true
      subscription_plman:
        description: Vul hier de subscription ID in van de "management" subscription (PL)
        required: true
      environment:
        type: environment

jobs:

  Add-Rootrights:
    uses: ./.github/workflows/1-pnk-addrootrights.yml
    with:
      Subscription_Id: ${{ github.event.inputs.subscription_lzid }}
      CustomerId: ${{ github.event.inputs.customerid }}
      CustomerFullName: ${{ github.event.inputs.customerfullname }}
      Location: 'westeurope'
    secrets: inherit
    
